### ISSUE TITLE
NixOS secrets storage.

### ISSUE THREAD

**Issue by TafkaMax** [xddxdd/nixos-config#1]
Hi I see you are using secrets encrypted with agenix in a separate repository. I am trying to do the same thing. Is there a way you could share your 'template' of nix code you are using in 'nixos-secrets' please?

**Comment by xddxdd** [comment]
Hi, there's no defined structure in my secrets repository, just a bunch of `.age` files. I reference the files in the form of `(inputs.secrets + "/path/to/secret.age")`.

**Comment by xddxdd** [comment]
Closed for inactivity.
